### <span style= "color:blue"> There are Two Most Important Data Structure in Python
    
**1_ Array** <br>
**2_ List**

### <span style= "color:orange"> Load in Numpy (Remember to pip install numpy first)

In [188]:
import numpy as np

### <span style= "color:blue"> Basics of Numpy

In [189]:
 #  Print 1D array
a = np.array([1,3,5])
print(a) 

[1 3 5]


In [190]:
 #  Print 2D array
b = np.array([[1.9,3.1,5.2],[9.0,0.8,7.6]])
print(b)

[[1.9 3.1 5.2]
 [9.  0.8 7.6]]


In [191]:
 #  Print 3D array
c = np.array([[1,3,5],[9,1,2],[9,8,7]])
print(c)

[[1 3 5]
 [9 1 2]
 [9 8 7]]


In [192]:
# get dimention Of the array
a.ndim

1

In [193]:
b.ndim

2

In [194]:
c.ndim

2

In [195]:
#Get Shape
b.shape

(2, 3)

In [196]:
c.shape

(3, 3)

In [197]:
# Get Data Type
a.dtype

dtype('int32')

In [198]:
c.dtype

dtype('int32')

In [199]:
# Get Total size
a.nbytes

12

In [200]:
# get Number of element
a.size

3

## ```Indexing and Slicing```
- ```Accessing / changing spacific Rows and Column Ect,```

- Rows and column starts from Zero

In [201]:
arr=np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [202]:
# Access the spacific elemet  [Rows , Column]
arr[1,5] 

13

In [203]:
# Get a spacific row
arr[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [204]:
arr[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [205]:
arr[:,:]     # : is ka matlb sub kuch caheay 

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [206]:
# Get a Spacific Column
arr[:,3] 

array([ 4, 11])

In [207]:
# Getting a litte more fancy [start Index: end Index: Step Size]
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [208]:
arr[0,2:-1]

array([3, 4, 5, 6])

In [209]:
arr[0,::2]

array([1, 3, 5, 7])

 ### <span style= "color:red">Initializing Different Types of Array

In [210]:
# The Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Be carefull When Copying  Arrays

- ***Orignal array can not be change  during change the array***

In [211]:
# Copy an array
a=np.array([9,8,7])
b=a.copy()
b[2]=100
print(a)
print(b)
print(a)

[9 8 7]
[  9   8 100]
[9 8 7]


### Mathematics

In [212]:
a=np.array([11,23,22,14])
print(a)

[11 23 22 14]


In [213]:
# Array to Array addition

In [214]:
print(a)
a+a

[11 23 22 14]


array([22, 46, 44, 28])

In [215]:
print(a)
a+2

[11 23 22 14]


array([13, 25, 24, 16])

In [216]:
print(a)
a-2

[11 23 22 14]


array([ 9, 21, 20, 12])

In [217]:
print(a)
a * 2

[11 23 22 14]


array([22, 46, 44, 28])

In [218]:
print(a)
a/2

[11 23 22 14]


array([ 5.5, 11.5, 11. ,  7. ])

In [219]:
b=np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [220]:
print(a)

[11 23 22 14]


In [221]:
a+b

array([12, 25, 25, 18])

In [222]:
print(a)
a**2   # Double Star ** mean Squre

[11 23 22 14]


array([121, 529, 484, 196], dtype=int32)

### Apply trigonomatric Function on an Array

In [223]:
# Take the Sin
print(a)

np.sin(a)


[11 23 22 14]


array([-0.99999021, -0.8462204 , -0.00885131,  0.99060736])

In [224]:
np.cos(a)


array([ 0.0044257 , -0.53283302, -0.99996083,  0.13673722])

In [225]:
print(b)
np.tanh(b)

[1 2 3 4]


array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [226]:
print(a)
np.exp(a)

[11 23 22 14]


array([5.98741417e+04, 9.74480345e+09, 3.58491285e+09, 1.20260428e+06])

In [227]:
print(a)
np.log(a)

[11 23 22 14]


array([2.39789527, 3.13549422, 3.09104245, 2.63905733])

# List vs Array

- Mathematical Operation list par Perform ni ho skty
- agr koi bi 1 no asy 4 ya a*4 ho ya scalar vector ho ga
- agr no [4,5] is form m aye ya vector kahlaye ga

In [228]:
# Craete a List
lst=[1,2,3,4]      # agr hm n list par math ka koi operation perform krn ho ho to 
                  # Hm List ko Array m Convert Krty han
print(lst)
type(lst)

[1, 2, 3, 4]


list

In [229]:
# concatinate a list
new_lst = [9,8,7]
lst+new_lst

[1, 2, 3, 4, 9, 8, 7]

In [230]:
# contect a list
#lst * 2
#lst+lst
m=np.array(lst)
print(m)
m+m  # Abb ya numpy array ha

[1 2 3 4]


array([2, 4, 6, 8])

In [231]:
type(m)

numpy.ndarray

In [232]:
# Adding list
lst+lst

[1, 2, 3, 4, 1, 2, 3, 4]

In [233]:
#Scalar Multiplication

print(lst)
lst*4


[1, 2, 3, 4]


[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [234]:
# - Append Method                    #Pending

### Statistics

In [235]:
stats=np.array([[1,2,3],[5,6,7]])
stats

array([[1, 2, 3],
       [5, 6, 7]])

In [236]:
# Get Minimum Number
np.min(stats)

1

In [237]:
#Get Maximum Number
print(stats)
np.max(stats)

[[1 2 3]
 [5 6 7]]


7

In [238]:
#Get Maximum Number
print(stats)
np.max(stats , axis=1)

[[1 2 3]
 [5 6 7]]


array([3, 7])

In [239]:
# Get the Sum of Array
print(stats)
np.sum(stats , axis=0)

[[1 2 3]
 [5 6 7]]


array([ 6,  8, 10])

In [240]:
# Get the Sum of Array
print(stats)
np.sum(stats , axis=1)

[[1 2 3]
 [5 6 7]]


array([ 6, 18])

### Bit About while Loop

In [241]:
i=10
while i<1:
    print(i)


# Great Job!